server:
  servlet:
    context-path: /veiculox
  port: 8080

spring:
  datasource:
    url: jdbc:postgresql://${DB_HOST:localhost}:${DB_PORT:5432}/${DB_NAME:veiculox}
    password: ${DB_PASSWORD:postgres}
    username: ${DB_USERNAME:postgres}
    driver-class-name: org.postgresql.Driver
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: none
    open-in-view: false